In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder

data = {
    'Color': ['Red', 'Blue', 'Green', 'Red', 'Blue', 'Green', 'Red', 'Green'],
    'Size': ['Small', 'Medium', 'Large', 'Medium', 'Large', 'Small', 'Large', 'Small'],
    'Target': [1, 0, 1, 1, 0, 0, 1, 1]
}

df = pd.DataFrame(data)

df

   Color    Size  Target
0    Red   Small       1
1   Blue  Medium       0
2  Green   Large       1
3    Red  Medium       1
4   Blue   Large       0
5  Green   Small       0
6    Red   Large       1
7  Green   Small       1

In [2]:
le = LabelEncoder()

df['Color_LabelEncoded'] = le.fit_transform(df['Color'])

df

   Color    Size  Target  Color_LabelEncoded
0    Red   Small       1                   2
1   Blue  Medium       0                   0
2  Green   Large       1                   1
3    Red  Medium       1                   2
4   Blue   Large       0                   0
5  Green   Small       0                   1
6    Red   Large       1                   2
7  Green   Small       1                   1

In [3]:
ord_enc = OrdinalEncoder(categories=[['Small', 'Medium', 'Large']])

df['Size_OrdinalEncoded'] = ord_enc.fit_transform(df[['Size']])

df

   Color    Size  Target  Color_LabelEncoded  Size_OrdinalEncoded
0    Red   Small       1                   2                  0.0
1   Blue  Medium       0                   0                  1.0
2  Green   Large       1                   1                  2.0
3    Red  Medium       1                   2                  1.0
4   Blue   Large       0                   0                  2.0
5  Green   Small       0                   1                  0.0
6    Red   Large       1                   2                  2.0
7  Green   Small       1                   1                  0.0

In [ ]:
data = pd.DataFrame({
    'Education': ['High School', 'Bachelor', 'Master', 'PhD', 'Bachelor']
})

data

education_mapping = {
    'High School': 0,
    'Bachelor': 1,
    'Master': 2,
    'PhD': 3
}

data['Education_OrdinalEncoded'] = data['Education'].map(education_mapping)

print(data)

     Education  Education_OrdinalEncoded
0  High School                         0
1     Bachelor                         1
2       Master                         2
3          PhD                         3
4     Bachelor                         1

In [9]:
ohe = OneHotEncoder()

ohe_df = pd.DataFrame()
ohe.fit_transform(df[['Color']]),
columns=ohe.get_feature_names_out(['Color'])


df = pd.concat([df, ohe_df], axis=1)

df

   Color    Size  Target  Color_LabelEncoded  Size_OrdinalEncoded
0    Red   Small       1                   2                  0.0
1   Blue  Medium       0                   0                  1.0
2  Green   Large       1                   1                  2.0
3    Red  Medium       1                   2                  1.0
4   Blue   Large       0                   0                  2.0
5  Green   Small       0                   1                  0.0
6    Red   Large       1                   2                  2.0
7  Green   Small       1                   1                  0.0

In [10]:
import pandas as pd

data = pd.DataFrame({
    'Vehicle': ['Car', 'Bike', 'Truck', 'Bike', 'Car']
})

data

  Vehicle
0     Car
1    Bike
2   Truck
3    Bike
4     Car

In [11]:
data_one_hot = pd.get_dummies(
    data,
    columns=['Vehicle'],
    prefix='Vehicle',
    drop_first=True
)

# Display the result
print(data_one_hot)

   Vehicle_Car  Vehicle_Truck
0         True          False
1        False          False
2        False           True
3        False          False
4         True          False